export const FETCHING_ENTERPRISE_INFO = 'FETCHING_ENTERPRISE_INFO';
export const FETCH_ENTERPRISE_INFO_SUCCESS = 'FETCH_ENTERPRISE_INFO_SUCCESS';
export const FETCH_ENTERPRISE_INFO_FAILURE = 'FETCH_ENTERPRISE_INFO_FAILURE';
export const MODIFYING_ADDRESS = 'MODIFYING_ADDRESS';
export const MODIFY_ADDRESS_SUCCESS = 'MODIFY_ADDRESS_SUCCESS';
export const MODIFY_ADDRESS_FAILURE = 'MODIFY_ADDRESS_FAILURE';
//team
export const ACTIVATING_TEAM = 'ACTIVATING_TEAM';
export const ACTIVATE_TEAM_SUCCESS = 'ACTIVATE_TEAM_SUCCESS';
export const ACTIVATE_TEAM_FAILURE = 'ACTIVATE_TEAM_FAILURE';
export const DESACTIVATING_TEAM = 'DESACTIVATING_TEAM';
export const DESACTIVATE_TEAM_SUCCESS = 'DESACTIVATE_TEAM_SUCCESS';
export const DESACTIVATE_TEAM_FAILURE = 'DESACTIVATE_TEAM_FAILURE';
export const DELETTING_TEAM = 'DELETTING_TEAM';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAILURE = 'DELETE_TEAM_FAILURE';
export const GETTING_TEAM_NOTES = 'GETTING_TEAM_NOTES';
export const GET_TEAM_NOTES_SUCCESS = 'GET_TEAM_NOTES_SUCCESS';
export const GET_TEAM_NOTES_FAILURE = 'GET_TEAM_NOTES_FAILURE';
//members
export const ACTIVATING_MEMBER = 'ACTIVATING_MEMBER';
export const ACTIVATE_MEMBER_SUCCESS = 'ACTIVATE_MEMBER_SUCCESS';
export const ACTIVATE_MEMBER_FAILURE = 'ACTIVATE_MEMBER_FAILURE';
export const DESACTIVATING_MEMBER = 'DESACTIVATING_MEMBER';
export const DESACTIVATE_MEMBER_SUCCESS = 'DESACTIVATE_MEMBER_SUCCESS';
export const DESACTIVATE_MEMBER_FAILURE = 'DESACTIVATE_MEMBER_FAILURE';
export const DELETTING_MEMBER = 'DELETTING_MEMBER';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_FAILURE = 'DELETE_MEMBER_FAILURE';
export const GETTING_NOTES = 'GETTING_NOTES';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE';
//DefaultValues
export const DELETTING_DEFAULTVALUE = 'DELETTING_DEFAULTVALUE';
export const DELETE_DEFAULTVALUE_SUCCESS = 'DELETE_DEFAULTVALUE_SUCCESS';
export const DELETE_DEFAULTVALUE_FAILURE = 'DELETE_DEFAULTVALUE_FAILURE';
export const UPDATING_VALUE = 'UPDATING_VALUE';
export const UPDATE_VALUE_SUCCESS = 'UPDATE_VALUE_SUCCESS';
export const UPDATE_VALUE_FAILURE = 'UPDATE_VALUE_FAILURE';
export const ADDING_VALUE = 'ADDING_VALUE';
export const ADD_VALUE_SUCCESS = 'ADD_VALUE_SUCCESS';
export const ADD_VALUE_FAILURE = 'ADD_VALUE_FAILURE';

//Awards
export const DELETTING_AWARD = 'DELETTING_AWARD';
export const DELETE_AWARD_SUCCESS = 'DELETE_AWARD_SUCCESS';
export const DELETE_AWARD_FAILURE = 'DELETE_AWARD_FAILURE';
//Enterprise MODIFY
export const MODIFYING_ENTERPRISE = 'MODIFYING_ENTERPRISE';
export const MODIFY_ENTERPRISE_SUCCESS = 'MODIFY_ENTERPRISE_SUCCESS';
export const MODIFY_ENTERPRISE_FAILURE = 'MODIFY_ENTERPRISE_FAILURE';
