export const FETCHING_ENTERPRISE_INFO = 'FETCHING_ENTERPRISE_INFO';
export const FETCH_ENTERPRISE_INFO_SUCCESS = 'FETCH_ENTERPRISE_INFO_SUCCESS';
export const FETCH_ENTERPRISE_INFO_FAILURE = 'FETCH_ENTERPRISE_INFO_FAILURE';
