export const FETCHING_ENTERPRISE_INFO = 'FETCHING_ENTERPRISE_INFO';
export const FETCH_ENTERPRISE_INFO_SUCCESS = 'FETCH_ENTERPRISE_INFO_SUCCESS';
export const FETCH_ENTERPRISE_INFO_FAILURE = 'FETCH_ENTERPRISE_INFO_FAILURE';
export const MODIFYING_ADDRESS = 'MODIFYING_ADDRESS';
export const MODIFY_ADDRESS_SUCCESS = 'MODIFY_ADDRESS_SUCCESS';
export const MODIFY_ADDRESS_FAILURE = 'MODIFY_ADDRESS_FAILURE';