export const FETCHING_TEAMS = 'FETCHING_TEAMS';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const FETCH_TEAMS_FAILURE = 'FETCH_TEAMS_FAILURE';
export const GETTING_HISTORIC_VALUES = 'GETTING_HISTORIC_VALUES';
export const GET_HISTORIC_VALUES_SUCCESS = 'GET_HISTORIC_VALUES_SUCCESS';
export const GET_HISTORIC_VALUES_FAILURE = 'GET_HISTORIC_VALUES_FAILURE';
