export const FETCHING_GENERAL_USER_INFO = 'FETCHING_GENERAL_USER_INFO';
export const FETCH_GENERAL_USER_INFO_SUCCESS = 'FETCH_GENERAL_USER_INFO_SUCCESS';
export const FETCH_GENERAL_USER_INFO_FAILURE = 'FETCH_GENERAL_USER_INFO_FAILURE';
