export const FETCHING_GENERAL_USER_INFO = 'FETCHING_GENERAL_USER_INFO';
export const FETCH_GENERAL_USER_INFO_SUCCESS = 'FETCH_GENERAL_USER_INFO_SUCCESS';
export const FETCH_GENERAL_USER_INFO_FAILURE = 'FETCH_GENERAL_USER_INFO_FAILURE';
export const CREATTING_ENTERPRISE = 'CREATTING_ENTERPRISE';
export const CREATE_ENTERPRISE_SUCCESS = 'CREATE_ENTERPRISE_SUCCESS';
export const CREATE_ENTERPRISE_FAILURE = 'CREATE_ENTERPRISE_FAILURE';
